import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.Fragment>
      {children}
    </React.Fragment>
  );
}
