import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import NavbarSidebar from "../_components/NavbarSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="app d-flex">
//           <NavbarSidebar />
//           <main className="content" style={{ width: '100%' }}>
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.Fragment>
      {children}
    </React.Fragment>
  );
}
